version: "3"

services:
  js:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: web-js
    volumes:
      - .:/var/www/application/
    working_dir: /var/www/application/
    command: sh -c "npm install && npm run build"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
